/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:653858:
  println("textarea1 - GTextArea >> GEvent." + event + " @ " + millis());

} //_CODE_:textarea1:653858:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:308221:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('a');
} //_CODE_:button2:308221:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:604378:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('d');
} //_CODE_:button3:604378:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:348760:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('w');
} //_CODE_:button4:348760:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:984108:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('s');
} //_CODE_:button5:984108:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:463221:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('p');
} //_CODE_:button6:463221:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:307542:
  println("button7 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('q');
} //_CODE_:button7:307542:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:628090:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  ardPort.write('r');
} //_CODE_:button1:628090:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  textarea1 = new GTextArea(this, 386, 5, 198, 377, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  textarea1.setText("Messages from Zumo");
  textarea1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  button2 = new GButton(this, 24, 162, 80, 30);
  button2.setText("A");
  button2.setTextBold();
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 178, 158, 80, 34);
  button3.setText("D");
  button3.setTextBold();
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 102, 121, 82, 28);
  button4.setText("W");
  button4.setTextBold();
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 100, 201, 80, 30);
  button5.setText("S");
  button5.setTextBold();
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 116, 164, 52, 26);
  button6.setText("STOP");
  button6.setTextBold();
  button6.addEventHandler(this, "button6_click1");
  button7 = new GButton(this, 98, 259, 89, 30);
  button7.setText("Border Detect");
  button7.setTextBold();
  button7.addEventHandler(this, "button7_click1");
  button1 = new GButton(this, 94, 316, 93, 30);
  button1.setText("Entering room");
  button1.setTextBold();
  button1.addEventHandler(this, "button1_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextArea textarea1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
GButton button7; 
GButton button1; 